name: dir2msgstr
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'InfinityMods/Ascension'
    steps:
      - name: Echo github.repository
        shell: pwsh
        run: "github.repository: ${github.repository}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: dir2msgstr
        uses: BGforgeNet/msg2po@master
        with:
          push: true
          dir2msgstr: true
